version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NEXT}
      - POSTGRES_USER=${POSTGRES_USER_NEXT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_NEXT}

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_NEXT}
      - POSTGRES_DB=${POSTGRES_DB_NEXT}
      - POSTGRES_USER=${POSTGRES_USER_NEXT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_NEXT}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD_NEXT}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER_NEXT}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS_NEXT}
    depends_on:
      - db

volumes:
  db:
  nextcloud: