version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /Sistemas/nextcloud/pg/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NEXT}
      - POSTGRES_USER=${POSTGRES_USER_NEXT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_NEXT}

  app:
    image: nextcloud:24-apache
    restart: always
    volumes:
      - /Sistemas/nextcloud/html:/var/www/html
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_NEXT}
      - POSTGRES_DB=${POSTGRES_DB_NEXT}
      - POSTGRES_USER=${POSTGRES_USER_NEXT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_NEXT}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD_NEXT}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER_NEXT}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS_NEXT}
      - APACHE_DISABLE_REWRITE_IP=${NEXTCLOUD_DISABLE_IP}
      - TRUSTED_PROXIES=${TRUSTED_PROXY}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.terminal.rule=Host(`despacholahe.ddns.net`)"
      - "traefik.http.routers.terminal.entrypoints=web"
      - "traefik.http.routers.terminal.middlewares=https_redirect"

      - "traefik.http.routers.terminalsecured.rule=Host(`despacholahe.ddns.net`)"
      - "traefik.http.routers.terminalsecured.entrypoints=websecure"
      - "traefik.http.routers.terminalsecured.tls.certresolver=myresolver"

      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"


# Ya no hace falta añadirla a los servicios por que es la default
networks:
  default:
    external:
      name: traefik